[package]
name = "guidestone_core"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guidestone_proc_macro = { path = "../guidestone_proc_macro" }
bitflags = "2.4"
log = "0.4.20"
