[package]
name = "guidestone_winit"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guidestone_core = { path = "../guidestone_core" }
render_wgpu = { path = "../render_wgpu" }
winit = { git = "https://github.com/rust-windowing/winit.git", default-features = false, features = [
	"rwh_05",
	"x11",
	"wayland",
	"wayland-dlopen",
	"wayland-csd-adwaita",
] }
env_logger = "0.10.0"
log.workspace = true
futures-lite = "1.13.0"
