[package]
name = "guidestone_winit"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guidestone_core = { path = "../guidestone_core" }
render_wgpu = { path = "../render_wgpu" }
winit = { git = "https://github.com/rust-windowing/winit.git" }
env_logger = "0.10.0"
log = "0.4"
futures-lite = "1.13.0"
